// <auto-generated />
namespace MySQL_Dal_CodeFirst.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AenderungSchreibweiseIdnachID : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AenderungSchreibweiseIdnachID));
        
        string IMigrationMetadata.Id
        {
            get { return "201809042337336_Aenderung Schreibweise Id nach ID"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
